#!/bin/bash

echo "======================================"
echo "  Access URLs for Laporan System"
echo "======================================"
echo ""

echo "✅ Using Ingress (path-based routing)"
echo ""
echo "📱 Access your applications:"
echo "-----------------------------------"
echo "👤 User Interface:  http://localhost/user"
echo "🔧 Admin Interface: http://localhost/admin"
echo ""
echo "🔌 API Endpoints (for testing):"
echo "-----------------------------------"
echo "🔑 User Auth:       http://localhost/api/warga/auth/*"
echo "📝 User Reports:    http://localhost/api/warga/laporan"
echo "🔑 Admin Auth:      http://localhost/api/admin/auth/*"
echo "📊 Admin Reports:   http://localhost/api/admin/laporan"
echo ""
echo "💡 Check Ingress status:"
echo "-----------------------------------"
echo "kubectl get ingress"
echo "kubectl describe ingress laporan-ingress"
echo ""
